---
title: "Analysis on housing prices"
author: "Yena Joo"
date: "19/12/2020"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#tinytex::install_tinytex()
library(kableExtra)
library(knitr)
library(tidyverse)
library(gridExtra)
options(scipen = 999)
data <- read.csv("housingprice/data.csv")
```
# Abstract 

# Keywords

# Introduction

# Methodology

## Data
```{r}
housing_data <- select(data, -date, -waterfront, -view, -street, -city, -statezip, -country)
#housing_data
kable(head(housing_data), "latex", booktabs = T, align = "c")%>% 
  kable_styling(position = "center")
plot1<- ggplot(housing_data, aes(x = sqft_lot, y = price)) +
    geom_point() + ggtitle("Figure 1: before adjusting")
```
outliers should be omitted  
```{r}
#newdata <- data.frame()
#for(i in 1:length(housing_data) ) {
  #if(housing_data$price[i] >= 10000000 | housing_data$sqft_lot >= 600000){
   #newdata <-  rbind(housing_data , housing_data[i,]) }}
housing_data <- filter(housing_data, price <= 7000000 ) 
housing_data <- filter(housing_data, sqft_living <= 8000 )
plot2<- ggplot(housing_data, aes(x = sqft_living, y = price)) +
    geom_point() + ggtitle("Figure 2: adjusted")
grid.arrange(plot1, plot2, ncol=2)
```

## Model

```{r}
options(scipen = 999)
summary(lm(price ~ bedrooms + sqft_living + bathrooms + bedrooms*sqft_living, data = housing_data))
summary(lm(price ~ bedrooms + bathrooms, data = housing_data))
model <- lm(price ~ bedrooms + bathrooms + sqft_living + floors + yr_built, data = housing_data)
kable(broom::tidy(summary(model)), "latex", booktabs = T, align = "c") %>% 
  kable_styling(position = "center")
ggplot(housing_data, aes(x = bedrooms + bathrooms + sqft_living + floors + yr_built, y = price)) + 
  geom_point() +
  stat_smooth(method = "lm", col = "red") + ggtitle("regression")

#ggplotRegression(lm(price ~ bedrooms + bathrooms + sqft_living + floors + yr_built, data = housing_data))
#abline(price ~ bedrooms + bathrooms + sqft_living + floors + yr_built)
```

if yr_renovated == 0, treatment = 0 
```{r}
#make variables for control/treatment/time group
housing_data <- housing_data %>% 
  mutate(treatment_group = case_when(
    yr_renovated != 0 ~ 1, 
    yr_renovated == 0 ~ 0 ))
housing_data <- housing_data %>% 
  mutate(time = sample(0:1, length(price), replace=T))



# visualize
housing_data$treatment_group <- 
  as.factor(housing_data$treatment_group)

housing_data$time <- 
  as.factor(housing_data$time)

housing_data %>% 
  ggplot(aes(x = time,
             y = price,
             color = treatment_group)) +
  geom_point() +
  geom_line(aes(group = price), alpha = 0.5) +
  theme_minimal() +
  labs(x = "Time period",
       y = "price",
       color = "renovated") +
  scale_color_brewer(palette = "Set1")


```

# Results 

# Discussion

## Summary

## Conclusions 


## Weaknesses 

## Next Steps

# Reference

1. linear regression assumptions: https://www.statology.org/linear-regression-assumptions/
2. ggplot regression: https://sejohnston.com/2012/08/09/a-quick-and-easy-function-to-plot-lm-results-in-r/
3. exponential notation: https://stackoverflow.com/questions/9397664/force-r-not-to-use-exponential-notation-e-g-e10
4. ggplot side by side: https://stackoverflow.com/questions/1249548/side-by-side-plots-with-ggplot2
